### ISSUE TITLE
III.6.3 Solution Incorrect

### ISSUE THREAD

**Issue by Frank-9976** [hooyuser/Solution-to-Algebra-Chapter-0#14]
x = p((p − id_M)x) ∈ M is an incorrect assertion.

**Comment by hooyuser** [comment]
Thank you @Frank-9976 for bringing this to my attention. I've reviewed the section you mentioned and realized this evident mistake. Now you can take a look at the updated proof when you have a moment, and let me know if there are any other concerns. 

If everything looks good to you, feel free to close this issue, or let me know and I can close it. Thanks for your contribution!

**Comment by Frank-9976** [comment]
Looks good to me.
